title: Text Along
description: Our tool “Text Along - Subjectivity Analysis Support for Social Impact”, can assist users evaluate the likelihood of provided text in negatively or positively skewing their reader’s perceptions.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
